// Auto-generated gift data from filenames
// Actual format: [Price]S_[Name].png
// ⚠️ IMPORTANT: Array is sorted by price for getTopGift() to work correctly

export const ALL_GIFTS = [
  { price: 15, name: "Bear", image: "/asset/Gifts/15S_Bear.png" },
  { price: 25, name: "Rosae", image: "/asset/Gifts/25S_Rosae.png" },
  { price: 40, name: "Lol Pops", image: "/asset/Gifts/40S_Lol Pops.png" },
  { price: 50, name: "Cake", image: "/asset/Gifts/50S_Cake.png" },
  { price: 50, name: "GiftBox", image: "/asset/Gifts/50S_GiftBox.png" },
  { price: 100, name: "Flowers", image: "/asset/Gifts/100S_Flowers.png" },
  { price: 300, name: "Instant Ramens", image: "/asset/Gifts/300S_Instant Ramens.png" },
  { price: 300, name: "Xmas Stockings", image: "/asset/Gifts/300S_Xmas Stockings.png" },
  { price: 320, name: "Spring Baskets", image: "/asset/Gifts/320S_Spring Baskets.png" },
  { price: 330, name: "Swag Bags", image: "/asset/Gifts/330S_Swag Bags.png" },
  { price: 340, name: "Winter Wreaths", image: "/asset/Gifts/340S_Winter Wreaths.png" },
  { price: 350, name: "Jester Hats", image: "/asset/Gifts/350S_Jester Hats.png" },
  { price: 380, name: "Hex Pots", image: "/asset/Gifts/380S_Hex Pots.png" },
  { price: 400, name: "Easter Eggs", image: "/asset/Gifts/400S_Easter Eggs.png" },
  { price: 400, name: "Pool Floats", image: "/asset/Gifts/400S_Pool Floats.png" },
  { price: 400, name: "Restless Jars", image: "/asset/Gifts/400S_Restless Jars.png" },
  { price: 400, name: "Witch Hats", image: "/asset/Gifts/400S_Witch Hats.png" },
  { price: 420, name: "Magic Potions", image: "/asset/Gifts/420S_Magic Potions.png" },
  { price: 420, name: "Snoop Cigars", image: "/asset/Gifts/420S_Snoop Cigars.png" },
  { price: 430, name: "Desk Calendars", image: "/asset/Gifts/430S_Desk Calendars.png" },
  { price: 430, name: "Love Potions", image: "/asset/Gifts/430S_Love Potions.png" },
  { price: 440, name: "Fresh Socks", image: "/asset/Gifts/440S_Fresh Socks.png" },
  { price: 440, name: "Westside Signs", image: "/asset/Gifts/440S_Westside Signs.png" },
  { price: 450, name: "Top Hats", image: "/asset/Gifts/450S_Top Hats.png" },
  { price: 480, name: "Vice Creams", image: "/asset/Gifts/480S_Vice Creams.png" },
  { price: 500, name: "Ice Creams", image: "/asset/Gifts/500S_Ice Creams.png" },
  { price: 500, name: "Jolly Chimps", image: "/asset/Gifts/500S_Jolly Chimps.png" },
  { price: 500, name: "Sakura Flowers", image: "/asset/Gifts/500S_Sakura Flowers.png" },
  { price: 500, name: "Swiss Watches", image: "/asset/Gifts/500S_Swiss Watches.png" },
  { price: 510, name: "Input Keys", image: "/asset/Gifts/510S_Input Keys.png" },
  { price: 550, name: "Scared Cats", image: "/asset/Gifts/550S_Scared Cats.png" },
  { price: 555, name: "Clover Pins", image: "/asset/Gifts/555S_Clover Pins.png" },
  { price: 600, name: "Lush Bouquets", image: "/asset/Gifts/600S_Lush Bouquets.png" },
  { price: 600, name: "Victory Medals", image: "/asset/Gifts/600S_Victory Medals.png" },
  { price: 605, name: "Hypno Lollipops", image: "/asset/Gifts/605S_Hypno Lollipops.png" },
  { price: 650, name: "Valentine Boxes", image: "/asset/Gifts/650S_Valentine Boxes.png" },
  { price: 666, name: "Voodoo Dolls", image: "/asset/Gifts/666S_Voodoo Dolls.png" },
  { price: 700, name: "Heroic Helmets", image: "/asset/Gifts/700S_Heroic Helmets.png" },
  { price: 705, name: "Cookie Hearts", image: "/asset/Gifts/705S_Cookie Hearts.png" },
  { price: 750, name: "Moon Pendants", image: "/asset/Gifts/750S_Moon Pendants.png" },
  { price: 777, name: "Trapped Hearts", image: "/asset/Gifts/777S_Trapped Hearts.png" },
  { price: 800, name: "Snake Boxes", image: "/asset/Gifts/800S_Snake Boxes.png" },
  { price: 800, name: "Tama Gadgets", image: "/asset/Gifts/800S_Tama Gadgets.png" },
  { price: 850, name: "Bunny Muffins", image: "/asset/Gifts/850S_Bunny Muffins.png" },
  { price: 880, name: "Faith Amulets", image: "/asset/Gifts/880S_Faith Amulets.png" },
  { price: 900, name: "Bonded Rings", image: "/asset/Gifts/900S_Bonded Rings.png" },
  { price: 900, name: "Timeless Books", image: "/asset/Gifts/900S_Timeless Books.png" },
  { price: 950, name: "Crystal Balls", image: "/asset/Gifts/950S_Crystal Balls.png" },
  { price: 950, name: "Hearth", image: "/asset/Gifts/950S_Hearth.png" },
  { price: 950, name: "Holiday Drinks", image: "/asset/Gifts/950S_Holiday Drinks.png" },
  { price: 990, name: "Vintage Cigars", image: "/asset/Gifts/990S_Vintage Cigars.png" },
  { price: 1000, name: "Artisan Bricks", image: "/asset/Gifts/1000S_Artisan Bricks.png" },
  { price: 1100, name: "Electric Skulls", image: "/asset/Gifts/1100S_Electric Skulls.png" },
  { price: 1100, name: "Gem Signets", image: "/asset/Gifts/1100S_Gem Signets.png" },
  { price: 1100, name: "Neko Helmets", image: "/asset/Gifts/1100S_Neko Helmets.png" },
  { price: 1200, name: "Diamond Rings", image: "/asset/Gifts/1200S_Diamond Rings.png" },
  { price: 1200, name: "Heart Lockets", image: "/asset/Gifts/1200S_Heart Lockets.png" },
  { price: 1200, name: "Star Notepads", image: "/asset/Gifts/1200S_Star Notepads.png" },
  { price: 1300, name: "Astral Shards", image: "/asset/Gifts/1300S_Astral Shards.png" },
  { price: 1300, name: "Signet Rings", image: "/asset/Gifts/1300S_Signet Rings.png" },
  { price: 1300, name: "Skull Flowers", image: "/asset/Gifts/1300S_Skull Flowers.png" },
  { price: 1400, name: "Ion Gems", image: "/asset/Gifts/1400S_Ion Gems.png" },
  { price: 1400, name: "Party Sparklers", image: "/asset/Gifts/1400S_Party Sparklers.png" },
  { price: 1500, name: "Berry Boxes", image: "/asset/Gifts/1500S_Berry Boxes.png" },
  { price: 1500, name: "Cupid Charms", image: "/asset/Gifts/1500S_Cupid Charms.png" },
  { price: 1500, name: "Mighty Arms", image: "/asset/Gifts/1500S_Mighty Arms.png" },
  { price: 1500, name: "Santa Hats", image: "/asset/Gifts/1500S_Santa Hats.png" },
  { price: 1600, name: "Sky Stilettos", image: "/asset/Gifts/1600S_Sky Stilettos.png" },
  { price: 1800, name: "Rare Birds", image: "/asset/Gifts/1800S_Rare Birds.png" },
  { price: 1800, name: "Snow Mittens", image: "/asset/Gifts/1800S_Snow Mittens.png" },
  { price: 1900, name: "Mood Packs", image: "/asset/Gifts/1900S_Mood Packs.png" },
  { price: 2000, name: "Light Swords", image: "/asset/Gifts/2000S_Light Swords.png" },
  { price: 2026, name: "Big Years", image: "/asset/Gifts/2026S_Big Years.png" },
  { price: 2100, name: "Hanging Stars", image: "/asset/Gifts/2100S_Hanging Stars.png" },
  { price: 2100, name: "Record Players", image: "/asset/Gifts/2100S_Record Players.png" },
  { price: 2200, name: "Jingle Bells", image: "/asset/Gifts/2200S_Jingle Bells.png" },
  { price: 2200, name: "Mini Oscars", image: "/asset/Gifts/2200S_Mini Oscars.png" },
  { price: 2300, name: "Spy Agarics", image: "/asset/Gifts/2300S_Spy Agarics.png" },
  { price: 2400, name: "Sleigh Bells", image: "/asset/Gifts/2400S_Sleigh Bells.png" },
  { price: 2500, name: "Loot Bags", image: "/asset/Gifts/2500S_Loot Bags.png" },
  { price: 2600, name: "Precious Peaches", image: "/asset/Gifts/2600S_Precious Peaches.png" },
  { price: 2800, name: "Kissed Frogs", image: "/asset/Gifts/2800S_Kissed Frogs.png" },
  { price: 3100, name: "Mad Pumpkins", image: "/asset/Gifts/3100S_Mad Pumpkins.png" },
  { price: 3300, name: "Ionic Dryers", image: "/asset/Gifts/3300S_Ionic Dryers.png" },
  { price: 3500, name: "Money Pots", image: "/asset/Gifts/3500S_Money Pots.png" },
  { price: 4500, name: "Flying Brooms", image: "/asset/Gifts/4500S_Flying Brooms.png" },
  { price: 4799, name: "Toy Bears", image: "/asset/Gifts/4799S_Toy Bears.png" },
  { price: 5000, name: "Genie Lamps", image: "/asset/Gifts/5000S_Genie Lamps.png" },
  { price: 7500, name: "Low Riders", image: "/asset/Gifts/7500S_Low Riders.png" },
  { price: 12595, name: "Nail Bracelets", image: "/asset/Gifts/12595S_Nail Bracelets.png" },
  { price: 19047, name: "Stellar Rockets", image: "/asset/Gifts/19047S_Stellar Rockets.png" },
];

// Get drop items within price range
export function getGiftsInRange(minPrice, maxPrice) {
  return ALL_GIFTS.filter(g => g.price >= minPrice && g.price <= maxPrice);
}

// Get highest price gift from a list (for topGift)
export function getTopGift(gifts) {
  if (!gifts || gifts.length === 0) return ALL_GIFTS[0];
  return gifts[gifts.length - 1];
}
