// Auto-generated gift data from filenames
// Actual format: [Price]S_[Name].png
// ⚠️ IMPORTANT: Array is sorted by price for getTopGift() to work correctly

export const ALL_GIFTS = [
  { price: 15, name: "Bear", image: "/asset/Gifts/15S_Bear_Original_Bear.webp" },
  { price: 25, name: "Rosae", image: "/asset/Gifts/25S_Rosae_Original_Rosae.webp" },
  { price: 40, name: "Lol Pops", image: "/asset/Gifts/40S_Lol_Pops_Original_Lol_Pops.webp" },
  { price: 50, name: "Cake", image: "/asset/Gifts/50S_Cake_Original_Cake.webp" },
  { price: 50, name: "GiftBox", image: "/asset/Gifts/50S_GiftBox_Original_GiftBox.webp" },
  { price: 100, name: "Flowers", image: "/asset/Gifts/100S_Flowers_Original_Flowers.webp" },
  { price: 300, name: "Instant Ramens", image: "/asset/Gifts/300S_Instant_Ramens_Original_Instant_Ramens.webp" },
  { price: 300, name: "Xmas Stockings", image: "/asset/Gifts/300S_Xmas_Stockings_Original_Xmas_Stockings.webp" },
  { price: 320, name: "Spring Baskets", image: "/asset/Gifts/320S_Spring_Baskets_Original_Spring_Baskets.webp" },
  { price: 330, name: "Swag Bags", image: "/asset/Gifts/330S_Swag_Bags_Original_Swag_Bags.webp" },
  { price: 340, name: "Winter Wreaths", image: "/asset/Gifts/340S_Winter_Wreaths_Original_Winter_Wreaths.webp" },
  { price: 350, name: "Jester Hats", image: "/asset/Gifts/350S_Jester_Hats_Original_Jester_Hats.webp" },
  { price: 380, name: "Hex Pots", image: "/asset/Gifts/380S_Hex_Pots_Original_Hex_Pots.webp" },
  { price: 400, name: "Easter Eggs", image: "/asset/Gifts/400S_Easter_Eggs_Original_Easter_Eggs.webp" },
  { price: 400, name: "Pool Floats", image: "/asset/Gifts/400S_Pool_Floats_Original_Pool_Floats.webp" },
  { price: 400, name: "Restless Jars", image: "/asset/Gifts/400S_Restless_Jars_Original_Restless_Jars.webp" },
  { price: 400, name: "Witch Hats", image: "/asset/Gifts/400S_Witch_Hats_Original_Witch_Hats.webp" },
  { price: 420, name: "Magic Potions", image: "/asset/Gifts/420S_Magic_Potions_Original_Magic_Potions.webp" },
  { price: 420, name: "Snoop Cigars", image: "/asset/Gifts/420S_Snoop_Cigars_Original_Snoop_Cigars.webp" },
  { price: 430, name: "Desk Calendars", image: "/asset/Gifts/430S_Desk_Calendars_Original_Desk_Calendars.webp" },
  { price: 430, name: "Love Potions", image: "/asset/Gifts/430S_Love_Potions_Original_Love_Potions.webp" },
  { price: 440, name: "Fresh Socks", image: "/asset/Gifts/440S_Fresh_Socks_Original_Fresh_Socks.webp" },
  { price: 440, name: "Westside Signs", image: "/asset/Gifts/440S_Westside_Signs_Original_Westside_Signs.webp" },
  { price: 450, name: "Top Hats", image: "/asset/Gifts/450S_Top_Hats_Original_Top_Hats.webp" },
  { price: 480, name: "Vice Creams", image: "/asset/Gifts/480S_Vice_Creams_Original_Vice_Creams.webp" },
  { price: 500, name: "Ice Creams", image: "/asset/Gifts/500S_Ice_Creams_Original_Ice_Creams.webp" },
  { price: 500, name: "Jolly Chimps", image: "/asset/Gifts/500S_Jolly_Chimps_Original_Jolly_Chimps.webp" },
  { price: 500, name: "Sakura Flowers", image: "/asset/Gifts/500S_Sakura_Flowers_Original_Sakura_Flowers.webp" },
  { price: 500, name: "Swiss Watches", image: "/asset/Gifts/500S_Swiss_Watches_Original_Swiss_Watches.webp" },
  { price: 510, name: "Input Keys", image: "/asset/Gifts/510S_Input_Keys_Original_Input_Keys.webp" },
  { price: 550, name: "Scared Cats", image: "/asset/Gifts/550S_Scared_Cats_Original_Scared_Cats.webp" },
  { price: 555, name: "Clover Pins", image: "/asset/Gifts/555S_Clover_Pins_Original_Clover_Pins.webp" },
  { price: 600, name: "Lush Bouquets", image: "/asset/Gifts/600S_Lush_Bouquets_Original_Lush_Bouquets.webp" },
  { price: 600, name: "Victory Medals", image: "/asset/Gifts/600S_Victory_Medals_Original_Victory_Medals.webp" },
  { price: 605, name: "Hypno Lollipops", image: "/asset/Gifts/605S_Hypno_Lollipops_Original_Hypno_Lollipops.webp" },
  { price: 650, name: "Valentine Boxes", image: "/asset/Gifts/650S_Valentine_Boxes_Original_Valentine_Boxes.webp" },
  { price: 666, name: "Voodoo Dolls", image: "/asset/Gifts/666S_Voodoo_Dolls_Original_Voodoo_Dolls.webp" },
  { price: 700, name: "Heroic Helmets", image: "/asset/Gifts/700S_Heroic_Helmets_Original_Heroic_Helmets.webp" },
  { price: 705, name: "Cookie Hearts", image: "/asset/Gifts/705S_Cookie_Hearts_Original_Cookie_Hearts.webp" },
  { price: 750, name: "Moon Pendants", image: "/asset/Gifts/750S_Moon_Pendants_Original_Moon_Pendants.webp" },
  { price: 777, name: "Trapped Hearts", image: "/asset/Gifts/777S_Trapped_Hearts_Original_Trapped_Hearts.webp" },
  { price: 800, name: "Snake Boxes", image: "/asset/Gifts/800S_Snake_Boxes_Original_Snake_Boxes.webp" },
  { price: 800, name: "Tama Gadgets", image: "/asset/Gifts/800S_Tama_Gadgets_Original_Tama_Gadgets.webp" },
  { price: 850, name: "Bunny Muffins", image: "/asset/Gifts/850S_Bunny_Muffins_Original_Bunny_Muffins.webp" },
  { price: 880, name: "Faith Amulets", image: "/asset/Gifts/880S_Faith_Amulets_Original_Faith_Amulets.webp" },
  { price: 900, name: "Bonded Rings", image: "/asset/Gifts/900S_Bonded_Rings_Original_Bonded_Rings.webp" },
  { price: 900, name: "Timeless Books", image: "/asset/Gifts/900S_Timeless_Books_Original_Timeless_Books.webp" },
  { price: 950, name: "Crystal Balls", image: "/asset/Gifts/950S_Crystal_Balls_Original_Crystal_Balls.webp" },
  { price: 950, name: "Hearth", image: "/asset/Gifts/950S_Hearth_Original_Hearth.webp" },
  { price: 950, name: "Holiday Drinks", image: "/asset/Gifts/950S_Holiday_Drinks_Original_Holiday_Drinks.webp" },
  { price: 990, name: "Vintage Cigars", image: "/asset/Gifts/990S_Vintage_Cigars_Original_Vintage_Cigars.webp" },
  { price: 1000, name: "Artisan Bricks", image: "/asset/Gifts/1000S_Artisan_Bricks_Original_Artisan_Bricks.webp" },
  { price: 1100, name: "Electric Skulls", image: "/asset/Gifts/1100S_Electric_Skulls_Original_Electric_Skulls.webp" },
  { price: 1100, name: "Gem Signets", image: "/asset/Gifts/1100S_Gem_Signets_Original_Gem_Signets.webp" },
  { price: 1100, name: "Neko Helmets", image: "/asset/Gifts/1100S_Neko_Helmets_Original_Neko_Helmets.webp" },
  { price: 1200, name: "Diamond Rings", image: "/asset/Gifts/1200S_Diamond_Rings_Original_Diamond_Rings.webp" },
  { price: 1200, name: "Heart Lockets", image: "/asset/Gifts/1200S_Heart_Lockets_Original_Heart_Lockets.webp" },
  { price: 1200, name: "Star Notepads", image: "/asset/Gifts/1200S_Star_Notepads_Original_Star_Notepads.webp" },
  { price: 1300, name: "Astral Shards", image: "/asset/Gifts/1300S_Astral_Shards_Original_Astral_Shards.webp" },
  { price: 1300, name: "Signet Rings", image: "/asset/Gifts/1300S_Signet_Rings_Original_Signet_Rings.webp" },
  { price: 1300, name: "Skull Flowers", image: "/asset/Gifts/1300S_Skull_Flowers_Original_Skull_Flowers.webp" },
  { price: 1400, name: "Ion Gems", image: "/asset/Gifts/1400S_Ion_Gems_Original_Ion_Gems.webp" },
  { price: 1400, name: "Party Sparklers", image: "/asset/Gifts/1400S_Party_Sparklers_Original_Party_Sparklers.webp" },
  { price: 1500, name: "Berry Boxes", image: "/asset/Gifts/1500S_Berry_Boxes_Original_Berry_Boxes.webp" },
  { price: 1500, name: "Cupid Charms", image: "/asset/Gifts/1500S_Cupid_Charms_Original_Cupid_Charms.webp" },
  { price: 1500, name: "Mighty Arms", image: "/asset/Gifts/1500S_Mighty_Arms_Original_Mighty_Arms.webp" },
  { price: 1500, name: "Santa Hats", image: "/asset/Gifts/1500S_Santa_Hats_Original_Santa_Hats.webp" },
  { price: 1600, name: "Sky Stilettos", image: "/asset/Gifts/1600S_Sky_Stilettos_Original_Sky_Stilettos.webp" },
  { price: 1800, name: "Rare Birds", image: "/asset/Gifts/1800S_Rare_Birds_Original_Rare_Birds.webp" },
  { price: 1800, name: "Snow Mittens", image: "/asset/Gifts/1800S_Snow_Mittens_Original_Snow_Mittens.webp" },
  { price: 1900, name: "Mood Packs", image: "/asset/Gifts/1900S_Mood_Packs_Original_Mood_Packs.webp" },
  { price: 2000, name: "Light Swords", image: "/asset/Gifts/2000S_Light_Swords_Original_Light_Swords.webp" },
  { price: 2026, name: "Big Years", image: "/asset/Gifts/2026S_Big_Years_Original_Big_Years.webp" },
  { price: 2100, name: "Hanging Stars", image: "/asset/Gifts/2100S_Hanging_Stars_Original_Hanging_Stars.webp" },
  { price: 2100, name: "Record Players", image: "/asset/Gifts/2100S_Record_Players_Original_Record_Players.webp" },
  { price: 2200, name: "Jingle Bells", image: "/asset/Gifts/2200S_Jingle_Bells_Original_Jingle_Bells.webp" },
  { price: 2200, name: "Mini Oscars", image: "/asset/Gifts/2200S_Mini_Oscars_Original_Mini_Oscars.webp" },
  { price: 2300, name: "Spy Agarics", image: "/asset/Gifts/2300S_Spy_Agarics_Original_Spy_Agarics.webp" },
  { price: 2400, name: "Sleigh Bells", image: "/asset/Gifts/2400S_Sleigh_Bells_Original_Sleigh_Bells.webp" },
  { price: 2500, name: "Loot Bags", image: "/asset/Gifts/2500S_Loot_Bags_Original_Loot_Bags.webp" },
  { price: 2600, name: "Precious Peaches", image: "/asset/Gifts/2600S_Precious_Peaches_Original_Precious_Peaches.webp" },
  { price: 2800, name: "Kissed Frogs", image: "/asset/Gifts/2800S_Kissed_Frogs_Original_Kissed_Frogs.webp" },
  { price: 3100, name: "Mad Pumpkins", image: "/asset/Gifts/3100S_Mad_Pumpkins_Original_Mad_Pumpkins.webp" },
  { price: 3300, name: "Ionic Dryers", image: "/asset/Gifts/3300S_Ionic_Dryers_Original_Ionic_Dryers.webp" },
  { price: 3500, name: "Money Pots", image: "/asset/Gifts/3500S_Money_Pots_Original_Money_Pots.webp" },
  { price: 4500, name: "Flying Brooms", image: "/asset/Gifts/4500S_Flying_Brooms_Original_Flying_Brooms.webp" },
  { price: 4799, name: "Toy Bears", image: "/asset/Gifts/4799S_Toy_Bears_Original_Toy_Bears.webp" },
  { price: 5000, name: "Genie Lamps", image: "/asset/Gifts/5000S_Genie_Lamps_Original_Genie_Lamps.webp" },
  { price: 7500, name: "Low Riders", image: "/asset/Gifts/7500S_Low_Riders_Original_Low_Riders.webp" },
  { price: 12595, name: "Nail Bracelets", image: "/asset/Gifts/12595S_Nail_Bracelets_Original_Nail_Bracelets.webp" },
  { price: 19047, name: "Stellar Rockets", image: "/asset/Gifts/19047S_Stellar_Rockets_Original_Stellar_Rockets.webp" },
];

// Get drop items within price range
export function getGiftsInRange(minPrice, maxPrice) {
  return ALL_GIFTS.filter(g => g.price >= minPrice && g.price <= maxPrice);
}

// Get highest price gift from a list (for topGift)
export function getTopGift(gifts) {
  if (!gifts || gifts.length === 0) return ALL_GIFTS[0];
  return gifts[gifts.length - 1];
}
